### ISSUE TITLE
[Feature Request]: Better handling of maximized presets

### ISSUE THREAD

**Issue by pasnox** [luisbocanegra/plasma-panel-colorizer#107]
- [x] I have searched if this feature hasn't been requested yet.

**Is your feature request related to a problem? Please describe.**
Currently the presets autoloading is working, but not as I would have expected.
In my case i'm interested about the maximized autoloading.
The maximized preset is unconditionally used if at least one window is maximized, being active or not, visible or not.

**Describe the solution you'd like**
Ideally, the maximized preset is set when at least one visible window is maximized. That mean that if I have an active main window maximized, it's enabled, and if i have an active non maximized window with a non active maximized window visible in the background it would be enabled as well.

**Comment by luisbocanegra** [comment]
Hi @pasnox, an option to filter by active windows for the maximized state has been added to preset auto-loading tab in [maximized-filter-by-active](https://github.com/luisbocanegra/plasma-panel-colorizer/tree/maximized-filter-by-active) branch

```
git clone https://github.com/luisbocanegra/plasma-panel-colorizer.git -b maximized-filter-by-active
cd plasma-panel-colorizer
kpackagetool6 -t Plasma/Applet -u package
```

![Screenshot_20241102_212744](https://github.com/user-attachments/assets/84b54269-7d60-4875-85d4-ebb0f69839c6)

**Comment by pasnox** [comment]
thanks I will have a look and report feedback

**Comment by pasnox** [comment]
Works fine, thanks!

**Comment by luisbocanegra** [comment]
You're welcome!

Thanks for the feedback, closing this now.
