### ISSUE TITLE
[Feature] Hide the outline in maximized mode

### ISSUE THREAD

**Issue by gabrielsantanaa** [luisbocanegra/plasma-panel-colorizer#11]
The oulined is a very good feature, but would be better if it can be hided on maximized mode.

**Comment by luisbocanegra** [comment]
Makes sense, I think a separate profile where you can have different settings that trigger on maximized/floating could be nice, just have to figure out how to do https://github.com/luisbocanegra/plasma-panel-colorizer/issues/9

**Comment by luisbocanegra** [comment]
This is now tracked by https://github.com/luisbocanegra/plasma-panel-colorizer/issues/23
