### ISSUE TITLE
[Bug]: Custom border width doesn't work with radius.

### ISSUE THREAD

**Issue by sagar297** [luisbocanegra/plasma-panel-colorizer#119]
custom border width doesn't looks right when using with radius.

![Screenshot_20241110_143642](https://github.com/user-attachments/assets/60c36f9e-9448-45cd-acb8-2bcb34123500)

with border width 1
![Screenshot_20241110_144248](https://github.com/user-attachments/assets/d2a57b90-f8c5-4e61-9182-33fe37038f4c)

**Comment by luisbocanegra** [comment]
This is expected, the custom borders are just rectangles drawn on each side, so they are more suited for less rounded or rectangle shapes.
