### ISSUE TITLE
[Bug]: No presets after installing manually with `./install.sh`

### ISSUE THREAD

**Issue by blackwingsdirk** [luisbocanegra/plasma-panel-colorizer#129]
I have:

- [ ] Searched if this issue hasn't been reported yet.
 > was told to report it by Luis

- [ ] Verified that I am using the latest version (see *Widget settings* > *About page* or *top right corner for version 1.1.0 and later*), **should be the same as [https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest](https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest)**
> 1.2.0

**Describe the bug**
Blew away ~.config/panel-colorizer dir from previous (manual) install, installed 1.2 via "get new widgets...".

**To Reproduce**

1. rm -rf ~/.config/panel-colorizer
2. KDE right-click context menu on panel/dock, "Add Widgets..." > "Get New Widgets..." > search for Panel Colorizer and install it, add it to dock/panel.
3. Right-click context on Colorizer, "Configure Panel colorizer".
4. Look at Presets. Empty.

dave@fin:~/.config/panel-colorizer$ ls -ld; ls -ltRra
drwxrwxr-x 3 dave dave 4096 Dec 17 16:10 .
.:
total 12
drwxrwxr-x  2 dave dave 4096 Dec 17 16:10 presets
drwxrwxr-x  3 dave dave 4096 Dec 17 16:10 .
drwx------ 55 dave dave 4096 Dec 17 17:10 ..

./presets:
total 8
drwxrwxr-x 3 dave dave 4096 Dec 17 16:10 ..
drwxrwxr-x 2 dave dave 4096 Dec 17 16:10 .

OS: Kubuntu 24.10 x86_64 (technically it was Ubuntu 24.04 LTS on initial install, but I gutted Gnome and installed all things KDE)
Host: XPS 15 9520 
Kernel: 6.11.0-1007-lowlatency 
Uptime: 22 hours, 42 mins 
Packages: 3055 (dpkg), 22 (snap) 
Shell: bash 5.2.32 
Resolution: 3440x1440 
DE: Plasma 6.1.5 
WM: KWin 
Theme: Breeze-Dark [GTK2], Breeze [GTK3] 
Icons: Vivid-Dark-Icons [GTK2/3] 
Terminal: konsole 
Terminal Font: Hack 9 
CPU: 12th Gen Intel i9-12900HK (20) @ 4.900GHz 
GPU: NVIDIA GeForce RTX 3050 Ti Mobile 
GPU: Intel Alder Lake-P GT2 [Iris Xe Graphics] 
Memory: 9515MiB / 31763MiB 

QMake version 3.1
Using Qt version 6.6.2 in /usr/lib/x86_64-linux-gnu

**Comment by luisbocanegra** [comment]
Hi, please you run this command `journalctl -f` from terminal, then open the widget settings, and paste here the output of the command?

**Comment by luisbocanegra** [comment]
> EDIT again: By process of elimination (unloading widgets to just have one at a time) determined it is in fact KDE Material You Colors causing the recurring JSON parse error.

Thanks, sorry for the log spam, the kde-material-you-colors widget expects kde-material-you-colors to be running and `/tmp/kde-material-you-colors-$(whoami).json` to exist, will fix that in the next version.

> I think I should remove _everything_ again - not just config dir for colorizer but rm -rf ~/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer and then re-log in and re-try adding it to see if it retains missing permission, just to rule out that the perm wasn't set originally by the manual install and not updated by the prebuilt widget add.

Did it work? In my case if I remove that folder and reinstall the widget from _Get new widgets_ the script has executable permission and I see the presets in the widget settings.

**Comment by luisbocanegra** [comment]
Thanks, then the problem is only with the manual install, I will change the title of the issue to reflect that
