### ISSUE TITLE
Updated to plasma 6, Widget is not functioning

### ISSUE THREAD

**Issue by teynav** [luisbocanegra/plasma-panel-colorizer#21]
I have version 3.0 and it gives

```
file:///home/navtey/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/main.qml:68:5: Type CompactRepresentation unavailable

file:///home/navtey/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/CompactRepresentation.qml:30:9: Type Components.PlasmoidIcon unavailable

file:///home/navtey/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/components/PlasmoidIcon.qml:23:5: PlasmaCore.SvgItem is not a type
```

**Comment by luisbocanegra** [comment]
Please install the Plasma 6 version https://store.kde.org/p/2130967, it may require removing the plasma 5 version first

**Comment by luisbocanegra** [comment]
Sorry I went straight to the error and ignored you said you have 0.3.0. But it seems you don't, according to those errors you are still using the plasma 5 version. If the update doesn't show or isn't able to install 0.3.0 properly follow those steps https://github.com/luisbocanegra/plasma-panel-colorizer/issues/16
