### ISSUE TITLE
Arch Update Checker displays incorrectly

### ISSUE THREAD

**Issue by Kevadroz** [luisbocanegra/plasma-panel-colorizer#31]
With panel colorizer: ![incorrect](https://github.com/luisbocanegra/plasma-panel-colorizer/assets/16049149/621b0d02-5226-4554-8265-da4428b93dd3)
Without panel colorizer: ![correct](https://github.com/luisbocanegra/plasma-panel-colorizer/assets/16049149/b1a7355e-de6e-48f5-adf8-7de770386e12)

As can be seen in the first image the text is tinted the same color as the circular background, making it impossible to read.

**Comment by luisbocanegra** [comment]
I can add an exception for not coloring things other than the icons for specific widgets I think that might work for a wide range of widgets aren't explicitly focused in displaying text.

Optionally you could ask the developer of that widget if they would like to use `org.kde.plasma.workspace.components BadgeOverlay` componen as a suggestion, as that component displays correctly with this widget:

![image](https://github.com/luisbocanegra/plasma-panel-colorizer/assets/15076387/a8ae412d-0810-439a-9d93-c095f3176fe9)

Is somewhat limited to what widget developers can do freely with their own components so don't expect them to accept your suggestion.

**Comment by Kevadroz** [comment]
> Optionally you could ask the developer of that widget if they would like to use org.kde.plasma.workspace.components BadgeOverlay component as a suggestion, as that one displays correctly with this widget:

Done in https://github.com/dhruv8sh/arch-update-checker/issues/3#issuecomment-2002160061

> Is somewhat limited compared to what widget developers can do freely with their own components, so don't expect them to accept your suggestion.

Yeah, I don't think that one will go anywhere.

**Comment by dhruv8sh** [comment]
I am the developer for the original applet @Kevadroz mentioned.
![image](https://github.com/luisbocanegra/plasma-panel-colorizer/assets/67322047/84cc14f3-c36f-4409-b0a7-4e5071aaef2c)
Including BadgeOverlay might not solve this either. For most colors provided by default, it too has a very low contrast.

**Comment by luisbocanegra** [comment]
BadeOverlay is fixed in the latest version, still widgets should be free to display elements and colors as they please so I either come up with a workaround or improve the exclusion so doesn't touch those widgets at all when they are blacklisted.

**Comment by luisbocanegra** [comment]
Got it will probably require a toggle so doesn't affect some weird corner cases
![image](https://github.com/luisbocanegra/plasma-panel-colorizer/assets/15076387/b934adf0-72c5-4da0-b12f-d6a1cf685a37)
