### ISSUE TITLE
How can I reset the panel to the beginning

### ISSUE THREAD

**Issue by leodream** [luisbocanegra/plasma-panel-colorizer#32]
New to this widget and added it to my panel with full of widgets to give it a try. It completely change the color of every widgets once I dragged it to the panel without any confirmation, and I do not like how the panel looks.

Tried tuning its tons of options only made the panel looked worse. Removing the widget did not work either.

How can I reset the panel like I never added this widget?
Any help would be much appreciated.

**Comment by luisbocanegra** [comment]
> Changes to the panel are not permanent and can be removed by disabling them from widget settings or removing it from the panel and restarting Plasma or logging out.

**Comment by leodream** [comment]
Indeed, remove the widget, log out and log in again reverts all the change. Thanks!
