### ISSUE TITLE
Proposal: Don't apply any customization by default

### ISSUE THREAD

**Issue by luisbocanegra** [luisbocanegra/plasma-panel-colorizer#36]
Changing the panel appearance by just adding the widget to the panel, while showcasing what this widget is capable of, is too aggressive. For this reason I am considering leaving everything disabled by default, so users have a clean slate to build their own themes on.

This will also convert the button to "**restore the default profile**" into a "**remove all customizations**" button, which I think would be less confusing.

**Comment by Attacktive** [comment]
> For this reason I am considering leaving everything disabled by default, so users have a clean slate to build their own themes on.

Can't agree more.
I had hard time changing back the text color of blacklisted widgets on day one. :laughing:
