### ISSUE TITLE
Add possibility to define unified background areas

### ISSUE THREAD

**Issue by NyaomiDEV** [luisbocanegra/plasma-panel-colorizer#39]
I love the fact that this widget provides me with an easy way to have "floating islands", however I'd very much like to unify the background between the system tray and the clock.

The way I envision it is by adding a "background unifier" widget that unifies parts of the panel's custom backgrounds; so by adding this "special separator" between the systray and the clock, the background island between the two is shared.

(Or probably the inverse can be done, using panel separators also as background separators)

**Comment by luisbocanegra** [comment]
I like this idea, I think someone in the kreddit post suggested this but I forgot to make an issue for it.

I have to think of the implementation yet but a way I imagine it is something like this:

**Widget unifier/Join widget backgrounds**
1. <kbd>System tray</kbd> <kbd>Clock</kbd>
2. <kbd>Window Buttons</kbd> <kbd>Window Title</kbd>
3. <kbd>Select start widget</kbd> <kbd>Select end widget</kbd>
4. <kbd>Add new</kbd>

**Comment by luisbocanegra** [comment]
Actually, I think it makes more sense to implement it as the special separator you suggested, so it will work like the margins separator widget does.

1. Iterate through the widgets
2. If the "background unifier" is found start merging backgrounds
3. If the "background unifier" is found stop merging them

**Comment by luisbocanegra** [comment]
Finally got around implementing this 🎉

![Screenshot_20240928_144023](https://github.com/user-attachments/assets/6eb1d0d8-efa3-4b38-b7d4-08b4329fb4ad)

Managed to do it by removing the default spacing then adding margins on the left of each widget and it worked!

Just have to figure out how to automatically hide the shadows/border/radius (in the screenshot radius is being done through per-widget override settings)

**Comment by luisbocanegra** [comment]
Radius and border done, working on the shadows

![Screenshot_20240929_010100](https://github.com/user-attachments/assets/7bdb21f1-6ebf-43af-9afb-08567908d1f7)

**Comment by NyaomiDEV** [comment]
oh this looks incredible! :)
just in time for my laptop customization it seems!

**Comment by nikoraasu** [comment]
Great! Can't wait!

**Comment by luisbocanegra** [comment]
Okay this is fire!

Though the way to manage them not so much for now. Can someone test this?

![Screenshot_20240929_164932](https://github.com/user-attachments/assets/fb396c0a-674a-4f45-9369-07d411fcd4e5)

**Comment by luisbocanegra** [comment]
To update to the latest commits:

```
git clone https://github.com/luisbocanegra/plasma-panel-colorizer
cd plasma-panel-colorizer
kpackagetool6 -t Plasma/Applet -u package
```

Note that the configuration format has changed and could change again before the release so you will need to start a new one from scratch. Oh and user presets folder changed to `$HOME/.config/panel-colorizer/presets`

To also test the custom background blur run `./install.sh` but it requires some [additional dependencies](https://github.com/luisbocanegra/plasma-panel-colorizer#manually) first.
