### ISSUE TITLE
[BUG] Panel background color set option is not persistent

### ISSUE THREAD

**Issue by Yankwerks** [luisbocanegra/plasma-panel-colorizer#42]
The _Color set_ panel background option, which supposedly should correspond to the panelBgColorModeThemeVariant value on _plasma-org.kde.plasma.desktop-appletsrc_ is not saved nor loaded.

Basically whenever plasma is restarted, that option is reverted to its default value.

**Comment by luisbocanegra** [comment]
Thanks for the bug report I'm able to reproduce it.
