### ISSUE TITLE
Panel shadow on non floating panel

### ISSUE THREAD

**Issue by Yankwerks** [luisbocanegra/plasma-panel-colorizer#43]
Currently when using the "Hide" panel background option, its original shadow is also hidden.
This allows the panel to fully match the window decorations background color, as if it was also part of it:
![Screenshot_20240421_231205](https://github.com/luisbocanegra/plasma-panel-colorizer/assets/8250380/24f59766-b93a-4533-b045-3bed1b1f6e97)

However it comes with the side effect of making that same panel flat and dull when no window is maximized, due to its abstinence of a shadow:
![Screenshot_20240421_231223](https://github.com/luisbocanegra/plasma-panel-colorizer/assets/8250380/1d5fa6f6-e02c-4541-a03b-2ef737c34fbc)

This can be fixed by using colorizer's panel shadow option, however this option only works when the panel is of the floating type:
![Screenshot_20240421_231244](https://github.com/luisbocanegra/plasma-panel-colorizer/assets/8250380/4470b574-e4e1-46f7-9977-2660b9e6d658)

**Comment by luisbocanegra** [comment]
Yeah, I noticed this too. Unfortunately the shadows are part of the panel background svg, so I am not sure if I can make my own shadow to draw outside the panel area. Will have to look into this.

Something I also wish was possible is to create my own background blurs and contrast but there doesn't seem to be a way to do that either with native qml

**Comment by luisbocanegra** [comment]
After some testing it seems the only reason the custom shadow works in floating mode is because the panel seems to be rendering a bigger transparent area, thus making the shadows be still inside the panel area.

Since the shadows come from the plasma theme svg, the panel is able to draw them in some way so that it goes outside the panel, so loading our own svg and then try to modify on the fly is maybe the only way to achieve this.

**Comment by luisbocanegra** [comment]
Hi, thanks to the work done in c++ plugin  [Custom blur region for panel background #50](https://github.com/luisbocanegra/plasma-panel-colorizer/issues/50) it will be possible to keep the original background enabled with opacity 0 so the original shadow still renders outside the panel. In think this is a reasonable workaround for this problem

![image](https://github.com/luisbocanegra/plasma-panel-colorizer/assets/15076387/e351e5ef-ddbe-4bd6-b73a-9273cc08753d)

**Comment by luisbocanegra** [comment]
There is a rather hacky workaround that can be used now.

As I said before, the shadow it's its own separate thing so it does not depend on the shape of the blur mask, quickly inspecting the panel code it seems it process the SVGs to obtain the shadow https://github.com/KDE/plasma-workspace/blob/1ce7ff6ddd0e44c138232cd8dabba8b8471e860d/shell/panelshadows_p.h#L14 https://github.com/KDE/plasma-workspace/blob/1ce7ff6ddd0e44c138232cd8dabba8b8471e860d/shell/panelview.cpp#L1871

The result is a shadow that does not change with our custom background:

![Screenshot_20240925_151534](https://github.com/user-attachments/assets/7fb8bc1e-4e44-4f73-9b02-8165731ab8a4)

_And yes, we [still need a way to remove that shadow](https://github.com/luisbocanegra/plasma-panel-colorizer/issues/59) if we want to draw [blur on the custom background](https://github.com/luisbocanegra/plasma-panel-colorizer/issues/72)_


After the rewrite is now possible to set margins to the custom background, this can be used to add some space below the area of the panel so the shadow is shown (exaggerated) there:

![Screenshot_20240925_150116](https://github.com/user-attachments/assets/1ba28afb-d250-465d-9cf0-d01a3443497b)

With this now we can create two different presets and have them switch when a window is maximized

![Screenshot_20240925_150639](https://github.com/user-attachments/assets/558681a2-1cad-4b58-9290-219f58a4df48)

The downside is that there will be some resizing as things in the panel change to fit the new thickness:

[Screencast_20240925_151004.webm](https://github.com/user-attachments/assets/688839af-df0e-41c6-acac-bea5a9c6296e)

**Comment by luisbocanegra** [comment]
Another simpler way, if using solid custom background without margins, would be making a copy of that preset with the native background removed (formerly "Hide")

[Screencast_20240925_153641.webm](https://github.com/user-attachments/assets/dc987fc0-bc93-4965-91f1-f40d94478927)

**Comment by luisbocanegra** [comment]
Closing this as I think the above workarounds solve the problem

Actually removing just the Panel native shadow without removing the blur may not be possible but I am tracking that in [#59](https://github.com/luisbocanegra/plasma-panel-colorizer/issues/59) anyway.

**Comment by RedSnt** [comment]
I didn't quite understand the workaround, but I did try and autoload another preset, and weirdly enough, loading that other preset ("fake floating" in my case), then switching back to the custom one I had been working on removed the panel shadow outline. Not entirely sure how that helped..

**Comment by luisbocanegra** [comment]
> I didn't quite understand the workaround, but I did try and autoload another preset, and weirdly enough, loading that other preset ("fake floating" in my case), then switching back to the custom one I had been working on removed the panel shadow outline. Not entirely sure how that helped..

That sounds like it triggered a bug that makes them disappear these shadows can only be removed by disabling "Native panel background" option or removing them from the SVG files of the theme

**Comment by RedSnt** [comment]
> > I didn't quite understand the workaround, but I did try and autoload another preset, and weirdly enough, loading that other preset ("fake floating" in my case), then switching back to the custom one I had been working on removed the panel shadow outline. Not entirely sure how that helped..
> 
> That sounds like it triggered a bug that makes them disappear, these shadows can only be removed by disabling "Native panel background" option or removing them from the SVG files of the theme

You are correct, because I loaded an old custom profile without the native background enabled. I just fooled myself into believing I had fixed it, but to be fair, I had been awake for over 18 hours at that point 😅  

Searching around a bit gave a clue as to what to look for, was one of the `panel-background.svgz` files in the `/usr/shade/plama/desktoptheme/default` subfolders, either the solid/widgets or translucent/widgets one, I replaced them both with the shadows removed (for the Breeze themes).  

Thanks for all your hard work @luisbocanegra - only found your stuff a couple of days ago, but I'm really impressed by both Smart Video Wallpaper Reborn and Panel Colorizer. It's quite amazing how much personality you can add to KDE with just those two things installed.
