### ISSUE TITLE
Feature request: change panel background color based on touching window

### ISSUE THREAD

**Issue by dr460nf1r3** [luisbocanegra/plasma-panel-colorizer#44]
Heya! 
Latte used to support changing panel background color based on whatever window was touching it. 
If I remember correctly, this used to source a specific color. The current feature of drawing it from the system works well, however, it would be nice to be able to let the panel become translucent again when no window touches it.

Intended purpose:
![image](https://github.com/luisbocanegra/plasma-panel-colorizer/assets/12834713/2980743a-ea2f-459b-b372-ad35825e711d)

Being able to have aligned colors between top panel and titlebar/window when windows are maximized.

![image](https://github.com/luisbocanegra/plasma-panel-colorizer/assets/12834713/15e4d1f5-c434-4aef-97fc-af8a9177b409)

Then having it opaque would make the top bar less dominant while not having windows maximized. 

Thanks!

**Comment by luisbocanegra** [comment]
Currently in v0.5.1 you can create and switch between different presets based on the state of the panel/windows:
- Normal
- Floating
- Maximized window is shown

I remember seeing a panel property that returns whether or not a window is touching the panel, will look into adding that to preset auto-loading.

Note that this feature only looks right as long as the application follows the current Plasma colors, taking colors from the actual window would be an interesting challenge, but will require C++/Qt and understanding Plasma/KWin code (I barely know C++). That deserves its own issue 🙂

**Comment by dr460nf1r3** [comment]
Actually having the color changed depending on whether the window maximized would already suffice for my use case - if I understood you correctly that's already possible by creating profiles?

**Comment by luisbocanegra** [comment]
> Edit: yes it actually does say it right at the beginning, but I didn't make the connection to using it that way.

Yeah, maybe a better description of some of the features in the README and a bunch of "What is this" labels/buttons through the widget settings, or even a video tutorial could help.

**Comment by luisbocanegra** [comment]
Done in https://github.com/luisbocanegra/plasma-panel-colorizer/commit/deb615bc852b6091f4af028e20f967dc6762ef4e

**Comment by dr460nf1r3** [comment]
Awesome! Could you push this as a new release in KDE's store? 😊

**Comment by luisbocanegra** [comment]
Will do later today

**Comment by mateushonorato** [comment]
would it be possible to set a different color for each application?

**Comment by luisbocanegra** [comment]
> would it be possible to set a different color for each application?

Should be possible yes, I may look into that after the rewrite
