### ISSUE TITLE
Panel looses opacity setting

### ISSUE THREAD

**Issue by kneckergit** [luisbocanegra/plasma-panel-colorizer#49]
First of all: Thank you for this wonderful contribution to KDE.
I encountered a bug: When changing the backgrounds opacity of a panel (e.g. 50%), it will flip back to 100% whenever the monitor switches off (standby, monitor power saving, etc.).

**Comment by luisbocanegra** [comment]
Can reproduce, will try fixing that ASAP

**Comment by luisbocanegra** [comment]
Commit https://github.com/luisbocanegra/plasma-panel-colorizer/commit/813f8a3a042e4923ed8bea6e58f898f79c275f5f should fix this.

To test do one of these:

- Clone and run `./install.sh` (assuming the build dependencies are installed)
- Or clone and run `kpackagetool6 -t Plasma/Applet -u package/` inside the project (without [blur plugin](https://github.com/luisbocanegra/plasma-panel-colorizer/issues/50))
- Easiest, download the file below and run `plasmoid-panel-colorizer-v0.5.3.zip` (also without blur plugin)

[plasmoid-panel-colorizer-v0.5.3.zip](https://github.com/user-attachments/files/15685258/plasmoid-panel-colorizer-v0.5.3.zip)
