### ISSUE TITLE
grouping icons together (kind of like in a system tray)

### ISSUE THREAD

**Issue by nikoraasu** [luisbocanegra/plasma-panel-colorizer#58]
Hey, this is basically the best extension that's been made for plasma ever since latte dock died. It actually made me go back to plasma from Hyprland. I really appreciate your work!
All I am missing though, is the ability to group certain widgets together, so they have a single uniform background, rather than a separate background for each plasmoid.

If you have a trouble grasping what I mean, imagine a system tray full of icons but without the "tray" logic behind it (thus of course without the triangle also), that you could put any widgets into.

I created a simple mockup in gimp:
![image](https://github.com/luisbocanegra/plasma-panel-colorizer/assets/86488693/7e893de0-528e-42b9-8dec-77fab4be6a94)

In my opinion, such logic could be implemented into the colorizer, as a separate category called "grouping" where you pick widgets that should share a single background, or it could be a separate widget that you just drop plasmoids into.
How you would implement it though, is of course your choice :)

**Comment by luisbocanegra** [comment]
> Hey, this is basically the best extension that's been made for plasma ever since latte dock died. It actually made me go back to plasma from Hyprland. I really appreciate your work!

That's quite an achievement. Thanks! ❤️

> All I am missing though, is the ability to group certain widgets together, so they have a single uniform background, rather than a separate background for each plasmoid.
> In my opinion, such logic could be implemented into the colorizer, as a separate category called "grouping" where you pick widgets that should share a single background, or it could be a separate widget that you just drop plasmoids into. How you would implement it though, is of course your choice :)

This has already been requested in https://github.com/luisbocanegra/plasma-panel-colorizer/issues/39 don't have an estimate of when I will work on it but hopefully in the upcoming weeks.

Closing this one, feel free to drop your suggestions in the linked issue
