### ISSUE TITLE
icons in the panel get smaller

### ISSUE THREAD

**Issue by songhd** [luisbocanegra/plasma-panel-colorizer#65]
After adding panel-colorizer to the panel, the original tray icons and applicaion icons get smaller automatically.  

original look
![image](https://github.com/user-attachments/assets/9c8b3582-f63a-42bc-a52d-5767acbbbe07)
![image](https://github.com/user-attachments/assets/f5c3c2d2-2d0e-4bce-ae8b-73dd251ff1b6)

after look
![image](https://github.com/user-attachments/assets/ba35dfa1-ac47-460d-b982-ea6860e9712e)
![image](https://github.com/user-attachments/assets/a0db58eb-bf30-40b7-8ccc-35971d287873)

panel height: 40
Could we remain the icon size in this scenario?

**Comment by luisbocanegra** [comment]
Currently the widget forces the same margin for all the widgets, this is so the custom widget backgrounds have all the same height (or width for vertical panels). I will look into making that optional and only if the custom widget background is enabled

**Comment by luisbocanegra** [comment]
Next version will support leaving the default margins or overriding them (or any other option) for specific widgets:

![Screenshot_20240921_023852](https://github.com/user-attachments/assets/0cb0a9a2-9503-4413-a4c3-05afc8c7d3f7)


That will solve this issue.

Check the [v1.0.0 milestone](https://github.com/luisbocanegra/plasma-panel-colorizer/milestone/1) for the current progress
