### ISSUE TITLE
dynamic offset

### ISSUE THREAD

**Issue by zayronxio** [luisbocanegra/plasma-panel-colorizer#68]
It is possible to add the option of a dynamic offset that can use the width of another panel to modify the offset, this could help to customize the panel even more, and customizations similar to deepin v23 could be achieved, and more

**Comment by luisbocanegra** [comment]
I am not sure I understand what you mean by dynamic offset, please explain how it works in more detail

An illustration or video of said deepin feature would help.

**Comment by zayronxio** [comment]
The plasma panel has the offset property, it refers to the separation with the anchor point, basically it is a margin

**Comment by luisbocanegra** [comment]
If you mean a margin around the row of widgets the current version only supports this with horizontal panels with a fixed width if I recall correctly.

I am doing a full rewrite of the widget and the next version will support the aforementioned margin for both dynamic width and vertical panels.

If you mean a margin around the panel, like a fake floating panel without being actually floating the rewritten version will also allow that.

If this is still not what you meant I will need a draw or image that shows how the feature would work.
