### ISSUE TITLE
Presets not included?

### ISSUE THREAD

**Issue by cinnamonbunbuns** [luisbocanegra/plasma-panel-colorizer#75]
When I went to attempt to download this widget through KDE and use it there were no presets present. Is this a bug or intended behavior?

I am running OpenSuSE tumbleweed and KDE 6.1 if that helps at all.

**Comment by luisbocanegra** [comment]
Intended, there aren't any presets included in the current release. But they are planned for the next version see https://github.com/luisbocanegra/plasma-panel-colorizer/issues/54

Once the implementation is finished I will probably make an announcement for people to share some presets to be built-in

**Comment by cinnamonbunbuns** [comment]
No worries was trying to find one that would turn the panel jet black when
a window is maximizes against it that's all!

Look forward to the re-write!
