### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by Nasdrovia69** [luisbocanegra/plasma-panel-colorizer#81]
Hello 
I have error when i do ./install.sh   i have install cmake extra-cmake-modules libplasma plasma5support
but i don't understand this error : 

-- The C compiler identification is GNU 14.2.1
-- The CXX compiler identification is GNU 14.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Plugin Id: luisbocanegra.panel.colorizer
Version: 0.5.2
CMake Error at CMakeLists.txt:26 (find_package):
  By not providing "FindPlasma.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Plasma", but
  CMake did not find one.

  Could not find a package configuration file provided by "Plasma" with any
  of the following names:

    PlasmaConfig.cmake
    plasma-config.cmake

  Add the installation prefix of "Plasma" to CMAKE_PREFIX_PATH or set
  "Plasma_DIR" to a directory containing one of the above files.  If "Plasma"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
gmake: Makefile : Aucun fichier ou dossier de ce nom
gmake: *** Aucune règle pour fabriquer la cible « Makefile ». Arrêt.
CMake Error: Not a file: /home/nas/plasma-panel-colorizer/build/plasmoid/cmake_install.cmake
CMake Error: Error processing file: /home/nas/plasma-panel-colorizer/build/plasmoid/cmake_install.cmake
-- The C compiler identification is GNU 14.2.1
-- The CXX compiler identification is GNU 14.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Plugin Id: luisbocanegra.panel.colorizer
Version: 0.5.2
CMake Error at /usr/share/ECM/modules/ECMQueryQt.cmake:82 (message):
  No Qt6 qtpaths executable found.  Can't check QT_INSTALL_PREFIX as required
Call Stack (most recent call first):
  /usr/share/ECM/kde-modules/KDEInstallDirs6.cmake:197 (ecm_query_qt)
  /usr/share/ECM/kde-modules/KDEInstallDirs.cmake:15 (include)
  CMakeLists.txt:40 (include)

-- Configuring incomplete, errors occurred!
gmake: Makefile : Aucun fichier ou dossier de ce nom
gmake: *** Aucune règle pour fabriquer la cible « Makefile ». Arrêt.
CMake Error: Not a file: /home/nas/plasma-panel-colorizer/build/plugin/cmake_install.cmake
CMake Error: Error processing file: /home/nas/plasma-panel-colorizer/build/plugin/cmake_install.cmake

Please can you help me i don't understand i sucess to install whith previous User I am on Fedora 40 kde
Thank you

**Comment by luisbocanegra** [comment]
You need to install some development packages

[libplasma-devel](https://fedora.pkgs.org/40/fedora-x86_64/libplasma-devel-6.0.3-1.fc40.i686.rpm.html)
[plasma5support-devel](https://fedora.pkgs.org/40/fedora-aarch64/plasma5support-devel-6.0.3-1.fc40.aarch64.rpm.html)

And maybe others

Optionally you can just run `kpackagetool6 -t Plasma/Applet -i package` inside the project directory, replace -i with -u to upgrade.

Note that the options to blur behind the custom background areas will not work if installed this way but everything else will work as expected.

**Comment by Nasdrovia69** [comment]
296 MB of dependency I'm going to do without it, it's a shame I found it promising on my previous user, but now it's too invasive and after trying it out it doesn't work any better. 
Thanks all the same for your prompt reply.
