### ISSUE TITLE
Tray icons  can't be colored anymore?

### ISSUE THREAD

**Issue by hrqmonteiro** [luisbocanegra/plasma-panel-colorizer#83]
I returned to KDE today and installed the extensions, some months ago i were able to colorize things like the Spotify and KTorrent i have:

![image](https://github.com/user-attachments/assets/60c8992d-f659-41be-bc4b-59a14cf76f97)

But apparently i am not able to, they don't appear in the `Text and Icons` settings:

![image](https://github.com/user-attachments/assets/3b9bccb5-f122-4fca-aebf-2713e1fdb4c2)

Why?

**Comment by luisbocanegra** [comment]
Which version of Plasma are you in? I tested the latest release with Plasma 6.2 and can confirm is not working there.

But the main branch is working, probably because I rewrote most of the widget and now handles that better, is still a work in progress but I am hopping to be able to make a release in the upcoming weeks (hopefully less than that).

For now, you can try installing manually and report bugs if you feel like doing so.

**Comment by hrqmonteiro** [comment]
Well, thanks, i manually installed and now i can override the tray icons

But my question now is how can i properly set the panel to be transparent, like before? In the previous i was using 0.5 transparency and it was actually opacity

But now i am not able to replicate it?

Now:
![image](https://github.com/user-attachments/assets/16e6727f-472e-418a-bd8f-f8995963d4bd)

Before:
![image](https://github.com/user-attachments/assets/b41687bd-201d-4277-b7e4-3078548a32a4)

**Comment by hrqmonteiro** [comment]
Also, please, how can i apply the vertical margins on just one element, like before? I applied only on clock so it would not have two lines

**Comment by luisbocanegra** [comment]
> Well, thanks, i manually installed and now i can override the tray icons
> 
> But my question now is how can i properly set the panel to be transparent, like before? In the previous i was using 0.5 transparency and it was actually opacity
> 
> But now i am not able to replicate it?
> 

This should work, if is not working it's a bug. Also the control to change floating point values is broken I need to fix that, but for now clicking on the up/down buttons still changes the values and they show the correct value after switching setting tabs.

![image](https://github.com/user-attachments/assets/bf348652-9863-4c52-8e0c-c4be918c1df2)

Also note that there are two opacities, the one from the native background and the other from the custom background, they are controlled separately.

The labels are still confusing but I plan to improve that at some point. Any suggestions are welcome of course.

**Comment by hrqmonteiro** [comment]
> > Also, please, how can i apply the vertical margins on just one element, like before? I applied only on clock so it would not have two lines
> 
> This is now done through the Overrides tab:
> 
>     * create a New Override
> 
>     * Click on Edit
> 
>     * Adjust the margins
> 
>     * Below under widgets section assign the Override to the widgets you want
> 
> 
> ![image](https://private-user-images.githubusercontent.com/15076387/375837607-6319d7dc-4ca2-4861-a4ff-e41a2e0a980c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2OTYxODAsIm5iZiI6MTcyODY5NTg4MCwicGF0aCI6Ii8xNTA3NjM4Ny8zNzU4Mzc2MDctNjMxOWQ3ZGMtNGNhMi00ODYxLWE0ZmYtZTQxYTJlMGE5ODBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDAxMTgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmYjBiNmI2YjdmMWQ4MDk1NTBiYzU4NDhkNjE3ZDNhOTkyYTVjYmE2ODg0Njc5YWQxNTZjMWM5NmFjNDc1YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sLoT_SubgP2QGmOwD34kxBNkDSWfLLbKrFgaVO6F0iU)
> 
> The UI is more complex now but also a more powerful than before, again any suggestions on how to label things in a more clear way are welcome. If there needs to be a Wiki/Guide explaining how to use it we could do that too.

Tried that but i believe it's not working?


https://github.com/user-attachments/assets/c067a550-37e2-4588-8339-e6d13ee945f1

**Comment by luisbocanegra** [comment]
Hmm, can you save your settings into a preset and paste the contents of the settings.json file here please.

The file will be stored in `/home/$USER/.config/panel-colorizer/presets/PRESET_NAME/settings.json`

**Comment by luisbocanegra** [comment]
Also from the Overrides tab click on export and paste the contents of `/home/$USER/.config/panel-colorizer/overrides.json` here
