### ISSUE TITLE
[Bug]: Presets list is empty

### ISSUE THREAD

**Issue by HattoriSuzuki** [luisbocanegra/plasma-panel-colorizer#99]
- [x] I have searched if this issue hasn't been reported yet.

**Describe the bug**
Presets list is empty.

**To Reproduce**
1. From KDE panel, right click on Panel Colorizer icon
2. Click on Configure Panel colorizer
3. See Presets tab, the list is empty.
4. Attach terminal error output for command: `journalctl -f`
[journalctl-f.txt](https://github.com/user-attachments/files/17445372/journalctl-f.txt)

Output for `ls /$HOME/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/presets` command:
[ls-presets.txt](https://github.com/user-attachments/files/17445375/ls-presets.txt)

**Expected behavior**
Presets should be listed.

**Screenshots**
![presets](https://github.com/user-attachments/assets/5aad6022-ab9f-49e3-a965-642155870a39)
![presets-autoloading](https://github.com/user-attachments/assets/97d93e98-7124-46d2-8937-19c1adc589fa)

**Project version**
1.0.0

**Desktop (please complete the following information):**
- Operating System: KDE neon 6.2
- KDE Plasma Version: 6.2.1
- KDE Frameworks Version: 6.7.0
- Qt Version: 6.7.2
- Kernel Version: 6.8.0-47-generic (64-bit)
- Graphics Platform: Wayland

**Additional context**
None

**Comment by luisbocanegra** [comment]
Can you please open `/home/hattori/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/configPresets.qml` and add the following bellow line 56:

```
        target: runCommand
        function onExited(cmd, exitCode, exitStatus, stdout, stderr) {
            console.error(cmd, exitCode, exitStatus, stdout, stderr) // <- add this line
```

**Comment by luisbocanegra** [comment]
Also, what happens if you try to create a new preset, does it appear?

**Comment by HattoriSuzuki** [comment]
@luisbocanegra 

Here is the log after adding console.error:  
[journalctl-f-1.txt](https://github.com/user-attachments/files/17445578/journalctl-f-1.txt)

The error messages printed by console.error:

> Oct 19 21:05:57 hattori-notebook plasmashell[3028]: qml: mkdir -p '/home/hattori/.config/panel-colorizer/presets/' 0 0
Oct 19 21:05:57 hattori-notebook plasmashell[3028]: qml: find /home/hattori/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/presets/ -mindepth 1 -prune -type d -print0 | while IFS= read -r -d '' preset; do echo b:"$preset"; done | sort;find /home/hattori/.config/panel-colorizer/presets/ -mindepth 1 -prune -type d -print0 | while IFS= read -r -d '' preset; do echo u:"$preset"; done | sort 0 0  /bin/sh: 1: read: Illegal option -d
                                                /bin/sh: 1: read: Illegal option -d
                                                
I can't create new preset, after inputting preset name, press Save and take a screenshot, nothing happens.

**Comment by luisbocanegra** [comment]
Thanks, looks like the shell KDE Neon defaults to ([apparently dash](https://stackoverflow.com/questions/77600580/silent-read-illegal)) doesn't support the -d option for `read`.

Moving these commands to a separate bash script will fix this, I'll let you know once I have a branch for you to test.

**Comment by luisbocanegra** [comment]
Please try branch https://github.com/luisbocanegra/plasma-panel-colorizer/tree/empty-presets-fix

```
git clone https://github.com/luisbocanegra/plasma-panel-colorizer.git -b empty-presets-fix
cd plasma-panel-colorizer
kpackagetool6 -t Plasma/Applet -u package
```

**Comment by HattoriSuzuki** [comment]
@luisbocanegra Thank you for the updates. The fix is not working well for me. I am able to get it working by modify the fix:

File: /$HOME/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/configPresets.qml

Line 21 & 22, change from `sh` to `bash`:
> property string listUserPresetsCmd: "sh '" + toolsDir + "list_presets.sh' '" + presetsDir + "'"
> property string listBuiltinPresetsCmd: "sh '" + toolsDir + "list_presets.sh' '" + presetsBuiltinDir + "'"

to:

> property string listUserPresetsCmd: "bash '" + toolsDir + "list_presets.sh' '" + presetsDir + "'"
> property string listBuiltinPresetsCmd: "bash '" + toolsDir + "list_presets.sh' '" + presetsBuiltinDir + "'"

**Comment by luisbocanegra** [comment]
That's strange since the script itself is a bash script. What does it print you make it print the output like we did before?

**Comment by HattoriSuzuki** [comment]
@luisbocanegra It seems printing the same error about the Illegal option -d
[journalctl-f-2.txt](https://github.com/user-attachments/files/17463675/journalctl-f-2.txt)

**Comment by luisbocanegra** [comment]
Okay turns out I misunderstood the purpose of shebang (`#!/bin/env bash`) all this time... they are meant to be used when the script is called directly, and are ignored when calling with an explicit interpreter e.g. `sh script.sh`.

I was doing this because I assumed zip/KNewStuff/kpackagetool6 didn't save/set permissions but it seems they do, so executing the script directly should solve this.

Please try again branch [empty-presets-fix](https://github.com/luisbocanegra/plasma-panel-colorizer/tree/empty-presets-fix?rgh-link-date=2024-10-20T23%3A11%3A50Z)

**Comment by luisbocanegra** [comment]
Tried myself in a Neon VM and it's working
